#!/bin/bash
#==============================================================================
# Copyright (C) 2019-present Alces Flight Ltd.
#
# This file is part of Flight Diagnostics.
#
# This program and the accompanying materials are made available under
# the terms of the Eclipse Public License 2.0 which is available at
# <https://www.eclipse.org/legal/epl-2.0>, or alternative license
# terms made available by Alces Flight Ltd - please direct inquiries
# about licensing to licensing@alces-flight.com.
#
# Flight Diagnostics is distributed in the hope that it will be useful, but
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR
# IMPLIED INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OR CONDITIONS
# OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A
# PARTICULAR PURPOSE. See the Eclipse Public License 2.0 for more
# details.
#
# You should have received a copy of the Eclipse Public License 2.0
# along with Flight Diagnostics. If not, see:
#
#  https://opensource.org/licenses/EPL-2.0
#
# For more information on <project>, please visit:
# https://github.com/alces-flight/flight-diag
#==============================================================================
DIAG="$(which diag)"

view() {
  local file
  file="$1"
  sudo $DIAG logview "$file"
}

usage() {
  echo "Usage: $0 <file>"
cat <<EOF

  The supplied <file> argument may be specified as a fully-qualified path name
  (prefixed with /var/log) or as a relative path name (/var/log will be
  automatically applied).

EOF
}

main() {
  local f rc
  f="$1"

  view "$f"
  rc=$?
  if [ $rc -gt 0 ]; then
    echo "$0: problem viewing log: $f"
    return 1
  fi
}

if [ "$1" == "-h" -o "$1" == "--help" ]; then
  usage
elif [ -z "$1" ]; then
  usage
  exit 1
fi

main "$@"
