#!/bin/bash
###############################################################################
#: synopsis: View a file from /var/log (with 'cat')
#: user: root
#: help: |
#:   The logcat command allows access to view log files held in
#:   /var/log through 'cat'. This aids log retrieval for later use. The
#:   supplied file name may be specified as a fully-qualified path name
#:   (i.e. prefixed with /var/log) or a relative path name (/var/log
#;   will be automatically applied).
#:   
#:   Requires administrative access.
#: examples: |
#:     logcat messages
#:     logcat /var/log/cron
###############################################################################
PROGNAME="$(basename "$0")"
PATH=/bin:/usr/bin:/sbin:/usr/sbin
if [ -z "$1" ]; then
  echo "Usage: $PROGNAME <file>"
  exit 1
else
  logfile="$1"
  if [[ ! "$logfile" =~ ^/ ]]; then
    logfile="/var/log/$logfile"
  fi
  logfile=$(realpath --canonicalize-missing --quiet "$logfile")
  if [[ ! "$logfile" =~ ^/var/log ]]; then
    diag_err "$PROGNAME: file is not in /var/log: $1"
    exit 1
  else 
    if [ -f "$logfile" ]; then
      diag_log "$PROGNAME: viewing file: $logfile"
      cat "$logfile"
    else
      diag_err "$PROGNAME: file not found: $logfile"
      exit 1
    fi
  fi
fi
