#!/bin/bash
###############################################################################
#: synopsis: Tail a file from /var/log
#: user: root
#: help: |
#:   The logtail command allows access to log files held in /var/log for
#:   display via 'tail -f' (i.e. to continually display the most recent
#:   writes to the file). File names may be supplied as fully-qualified
#:   path names (i.e. prefixed with /var/log) or relative path names
#:   (/var/log will be automatically applied).
#:   
#:   Requires administrative access.
#: examples: |
#:     logtail messages
#:     logtail /var/log/cron /var/log/maillog
###############################################################################
PROGNAME="$(basename "$0")"
PATH=/bin:/usr/bin:/sbin:/usr/sbin

if [ -z "$1" ]; then
  echo "Usage: $PROGNAME FILE..."
  exit 1
else
  files=()
  for a in "$@"; do
    logfile="$a"
    if [[ ! "$logfile" =~ ^/ ]]; then
      logfile="/var/log/$logfile"
    fi
    logfile=$(realpath --canonicalize-missing --quiet "$logfile")
    if [[ ! "$logfile" =~ ^/var/log ]]; then
      diag_err "$PROGNAME: file is not in /var/log: $a"
      exit 1
    else 
      if [ -f "$logfile" ]; then
        files+=("$logfile")
      else
        diag_err "$PROGNAME: file not found: $logfile"
        exit 1
      fi
    fi
  done
  diag_log "$PROGNAME: using file list: ${files[@]}"
  tail -f "${files[@]}"
fi