#!/bin/bash
###############################################################################
#: synopsis: View a file from /var/log (with 'less')
#: user: root
#: help: |
#:   The logview command allows access to view log files held in
#:   /var/log through the 'less' pager. The supplied file name may be
#:   specified as a fully-qualified path name (i.e. prefixed with
#:   /var/log) or a relative path name (/var/log will be automatically
#:   applied).
#:   
#:   Requires administrative access.
#: examples: |
#:     logview messages
#:     logview /var/log/cron
###############################################################################
PROGNAME="$(basename "$0")"
PATH=/bin:/usr/bin:/sbin:/usr/sbin
export LESSSECURE=1
export LESS="${LESS:-RXM}"
if [ -z "$1" ]; then
  echo "Usage: $PROGNAME <file>"
  exit 1
else
  logfile="$1"
  if [[ ! "$logfile" =~ ^/ ]]; then
    logfile="/var/log/$logfile"
  fi
  logfile=$(realpath --canonicalize-missing --quiet "$logfile")
  if [[ ! "$logfile" =~ ^/var/log ]]; then
    diag_err "$PROGNAME: file is not in /var/log: $1"
    exit 1
  else 
    if [ -f "$logfile" ]; then
      diag_log "$PROGNAME: viewing file: $logfile"
      less "$logfile"
    else
      diag_err "$PROGNAME: file not found: $logfile"
      exit 1
    fi
  fi
fi
