#!/bin/bash
###############################################################################
#: synopsis: Access process list via top
#: help: |
#:   Convenience helper providing access to the 'top' command.
#:   
#:   Does not require administrative access.
#:   
#:   See 'top -h' for more details.
###############################################################################
PATH=/bin:/usr/bin:/sbin:/usr/sbin
top "$@"
